---

- hosts: localhost
  gather_facts: false
  connection: local
  user: remote

  tasks:
  - name: "Create a VM from a template"
    vmware_guest:
      hostname: vcenter.kuisc.com 
      username: m966m862
      password: Teksab10#
      validate_certs: no
      datacenter: Edwards
      folder: '/Classes/IT 416 - System Integration and Architecture/McCurry'
      template: Kali-Template
      name: IT416-Kali-McCurry
      resource_pool: IT 416 - System Integration and Architecture
      state: poweredon

      hardware:
        num_cpus: 4

      networks:
      - name: IT416_WAN
        ip: 192.168.5.245
        netmask: 255.255.255.0
        gateway: 192.168.5.254
        domain: internal.it416.com
        dns_servers:
        - 8.8.8.8
